"""add game_rooms and room_players tables

Revision ID: bb13ab81f224
Revises: 8bd4d27bac2f
Create Date: 2026-05-12 16:14:38.020497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb13ab81f224'
down_revision: Union[str, Sequence[str], None] = '8bd4d27bac2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'playing', 'finished', name='roomstatus'), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_rooms_id'), 'game_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_game_rooms_room_code'), 'game_rooms', ['room_code'], unique=True)
    op.create_table('room_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_players_id'), 'room_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_players_id'), table_name='room_players')
    op.drop_table('room_players')
    op.drop_index(op.f('ix_game_rooms_room_code'), table_name='game_rooms')
    op.drop_index(op.f('ix_game_rooms_id'), table_name='game_rooms')
    op.drop_table('game_rooms')
    # ### end Alembic commands ###
