"""update_missing_columns_for_quizzes

Revision ID: d73aad2bc6d2
Revises: d4dfc0a69f81
Create Date: 2026-05-11 09:45:29.929914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd73aad2bc6d2'
down_revision: Union[str, Sequence[str], None] = 'd4dfc0a69f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('host_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('quizzes_owner_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quizzes', 'updated_at')
    op.drop_column('quizzes', 'owner_id')
    op.drop_column('quizzes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('quizzes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_owner_id_fkey'), 'quizzes', 'users', ['owner_id'], ['id'])
    op.drop_column('quizzes', 'host_id')
    # ### end Alembic commands ###
